flip_pub:
  ros__parameters:

    controller_name: "joint_trajectory_controller"
    wait_sec_between_publish: 8

    goal_names: ["pos1", "pos2"]
    pos1:
      positions: [1.57, -1.15, 1.80, 5.2, 4.76, -4.62]            
    pos2:
      positions: [1.57, -1.15, 1.50, 3.00, 4.76, -4.62]
      velocities: [0.0, 0.0, 2.00, 3.33, 0.0, 0.0]
    ##pos3:
      ##positions: [0.814, -2.00, 1.68, -3.03, 5.17, -4.62]
      
    ##pos4:
      ##positions: [0.814, -2.00, 2.3, -0.97, 5.17, -4.62]
      ##
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

    check_starting_point: false
    starting_point_limits:
      shoulder_pan_joint: [-0.1,0.1]
      shoulder_lift_joint: [-1.6,-1.5]
      elbow_joint: [-0.1,0.1]
      wrist_1_joint: [-1.6,-1.5]
      wrist_2_joint: [-0.1,0.1]
      wrist_3_joint: [-0.1,0.1]
